// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/about.tsx";
import * as $1 from "./routes/index.tsx";
import * as $2 from "./routes/signin.tsx";
import * as $3 from "./routes/signup.tsx";
import * as $4 from "./routes/users/[userID].tsx";
import * as $$0 from "./islands/GoogleAd.tsx";
import * as $$1 from "./islands/LoginForm.tsx";
import * as $$2 from "./islands/NavBar.tsx";

const manifest = {
  routes: {
    "./routes/about.tsx": $0,
    "./routes/index.tsx": $1,
    "./routes/signin.tsx": $2,
    "./routes/signup.tsx": $3,
    "./routes/users/[userID].tsx": $4,
  },
  islands: {
    "./islands/GoogleAd.tsx": $$0,
    "./islands/LoginForm.tsx": $$1,
    "./islands/NavBar.tsx": $$2,
  },
  baseUrl: import.meta.url,
};

export default manifest;
